INSERT INTO  COMPANY (id, name)VALUES (1,'Coca-Cola');
INSERT INTO  COMPANY (id, name) VALUES (2,'IBM');
INSERT INTO  COMPANY (id, name) VALUES (3,'APPLE');
INSERT INTO  COMPANY (id, name) VALUES (4,'Nike');




INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (1,'IT',1);
INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES  (2,'Legal',1);
INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (3,'HR',1);
INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (4,'IT',2);
INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (5,'HR',2);
INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (6,'IT',3);
INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES  (7,'Legal',3);
INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (8,'HR',4);
INSERT INTO DEPARTMENT(ID, NAME, COMPANY_ID) VALUES (9,'IT',4);

INSERT INTO POSITIONTYPE (ID, position) VALUES (1,'SPECIALIST');
INSERT INTO POSITIONTYPE (ID, position) VALUES (2,'MANAGER');
INSERT INTO POSITIONTYPE (ID, position) VALUES (3,'DIRECTOR');

 INSERT INTO  USER (ID,NAME,LASTNAME,DATE_OF_BIRTH,POSITION_ID,DEPARTMENT_ID) VALUES
        (1,'Misha', 'Korol','1987-11-12',1,1),
        (2,'Vova', 'dib','1987-11-12',1,2),
        (3,'Sergiy', 'mar','1987-11-12',2,3),
        (4,'Yura', 'poli','1987-11-12',2,4),
        (5,'Rus', 'kon','1987-11-12',3,2),
        (6,'Sasha', 'stes','1987-11-12',1,3);

