--  create type positionUser as enum ('director','manager','specialist');

 create table company
(
   id int GENERATED BY DEFAULT AS IDENTITY,
    name_Company varchar(255) not null,
    primary key(id)
 );
 create table department
  (
    id int GENERATED BY DEFAULT AS IDENTITY,
     name_Department varchar(255) not null,
     user_id int,
    primary key(id)
 );
 create table user
  (
     id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) not null,
     last_Name varchar (255) not null,
   date_Of_Birth TIMESTAMP not null,

--      position_User positionUser,
    primary key(id)
 );
--  ALTER TABLE DEPARTMENT ADD FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY;
-- ALTER TABLE EMPLOYEE ADD  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT;